package com.kgurgul.cpuinfo.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF424242)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBBBBB)
val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFF0058CA)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001945)
val md_theme_light_tertiary = Color(0xFFD84315)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onTertiaryContainer = Color(0xFF410003)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFD)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFAFDFD)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF4FD8EB)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006874)
val md_theme_light_outlineVariant = Color(0x66BFC8CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF1C1C1C)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFFAAAAAA)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFF00429B)
val md_theme_dark_onSecondary = Color(0xFF002D6E)
val md_theme_dark_secondaryContainer = Color(0xFF00429B)
val md_theme_dark_onSecondaryContainer = Color(0xFFD9E2FF)
val md_theme_dark_tertiary = Color(0xFFD32F2F)
val md_theme_dark_onTertiary = Color(0xFF680008)
val md_theme_dark_tertiaryContainer = Color(0xFF930010)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE1E3E3)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E3)
val md_theme_dark_surfaceVariant = Color(0xFFE4E5E7)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_dark_inverseSurface = Color(0xFF2E3132)
val md_theme_dark_inversePrimary = Color(0xFF006874)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4FD8EB)
val md_theme_dark_outlineVariant = Color(0xE63F484A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1C1C1C)

val lightPrimary = Color(0x42, 0x42, 0x42)
val darkPrimary = Color(0x1c, 0x1c, 0x1c)
